### ISSUE TITLE
Upload dale to crates.io

### ISSUE THREAD

**Issue by talwat** [dustin4242/dale#1]
Hey dustin!

I think it would be cool if you would update dale to crates.io, which makes it a lot easier for people to try it out since they can just do `cargo install dale` or something like that. It's super easy too, just fill in some metadata in cargo.toml and then publish.

**Comment by dustin4242** [comment]
I will definitely consider this in the next few days when it becomes fully flushed out, I'll keep you posted if it happens!

**Comment by dustin4242** [comment]
Uploaded the latest version of dale to the crates.io repo and added a little readme to dale on how to install it :+1:
